---
title: "First Knit"
author: "Damian Earp"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended multiple high schools and ended up graduating from Learn 4 life. I excel in Math the best over English and found Math much easier then English, I did much better in Math then English because I understood Math much better then I did the majority of the other classes such as English.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
My computer is a Windows computer. For knowledge of computers, I would say I have a 7 in it. I have internet access at home and it is quite fast where I live

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  Damian is perfectly fine, unless you want to get creative. If I am called something else, I would not be very bothered, I just proffer Damian.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I have been fascinated with the way people make effects and edits to movies, videos online, and even being able to make other people laugh and watch something I made. I am looking forward to the Media design course, it looks the most interesting! I am aiming for my AA into Video Production and Design. 
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I haven't gone to any foreign country outside of the United states, I was given an opportunity to go to Germany but was declined for reasons, I was also given an opportunity to head to Japan but was also quickly declined, so I would love in the future to go to Germany and Japan. I have not served in the Military but it I was given a choice, I would want to be in the Combat branch.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




